version: "3.9"
services:
  rpps-service:
    build: ./api
    ports:
      - "5005:5005"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rpps-service.rule=Host(`rpps.flow-parents.com`)"
      - "traefik.http.routers.rpps-service.entrypoints=websecure"
      - "traefik.http.routers.rpps-service.tls=true"
      - "traefik.http.services.rpps-service.loadbalancer.server.port=5005"
    networks:
      - web

networks:
  web:
    external: true
